import { Link, useLocation } from "react-router-dom";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleAlert, Copy, Download, Eye, FileCheck2, FileText, Hash, Heart, Landmark, LockKeyhole, Search, ShieldCheck, Upload, Users } from "lucide-react";

const funds = [
  ["Quỹ Học tập", "Thấp", "Hỗ trợ học phí, tài liệu và hành trình học tập bền vững.", "1,245,000,000 ₫", 76],
  ["Quỹ Khẩn cấp", "Thấp", "Đồng hành kịp thời khi sinh viên gặp khó khăn đột xuất.", "382,500,000 ₫", 52],
  ["Quỹ Nghiên cứu", "TB", "Nuôi dưỡng các đề tài nghiên cứu có giá trị cho cộng đồng.", "690,000,000 ₫", 64],
  ["Quỹ Startup", "Cao", "Kết nối nguồn lực cho những ý tưởng khởi nghiệp sinh viên.", "420,000,000 ₫", 41],
  ["Quỹ Tình nguyện", "TB", "Lan tỏa những dự án thiện nguyện do sinh viên khởi xướng.", "278,000,000 ₫", 58],
  ["Quỹ Vùng cao", "Thấp", "Đem cơ hội học tập đến các vùng còn nhiều thiếu thốn.", "565,000,000 ₫", 72],
  ["Quỹ Phát triển Cộng đồng", "TB", "Tạo tác động lâu dài qua các sáng kiến vì cộng đồng.", "812,000,000 ₫", 68],
] as const;

const transactions = [
  ["SCF-2026-01842", "18/07/2026", "Đóng góp", "Quỹ Học tập", "+ 5.000.000 ₫", "Nguyễn Minh Anh", "Đã xác thực"],
  ["SCF-2026-01841", "18/07/2026", "Giải ngân", "Quỹ Vùng cao", "− 28.500.000 ₫", "Hội đồng quỹ", "Đã xác thực"],
  ["SCF-2026-01840", "17/07/2026", "Đóng góp", "Quỹ Khẩn cấp", "+ 1.000.000 ₫", "Mạnh thường quân ẩn danh", "Đã xác thực"],
  ["SCF-2026-01839", "17/07/2026", "Giải ngân", "Quỹ Nghiên cứu", "− 12.800.000 ₫", "Hội đồng quỹ", "Đã xác thực"],
];

const nav = [
  ["Trang chủ", "/"], ["Các quỹ", "/cac-quy"], ["Giao dịch", "/giao-dich"], ["Minh bạch", "/minh-bach"], ["Đóng góp", "/dong-gop"],
];

function PublicShell({ children }: { children: React.ReactNode }) {
  const { pathname } = useLocation();
  const active = pathname.startsWith("/cac-quy") ? "/cac-quy" : pathname.startsWith("/giao-dich") ? "/giao-dich" : pathname.startsWith("/minh-bach") || pathname === "/log-bat-bien" ? "/minh-bach" : pathname.startsWith("/dong-gop") ? "/dong-gop" : "/";
  return <div className="min-h-screen bg-[#F8FAFC] text-[#0F172A]">
    <header className="sticky top-0 z-20 h-20 border-b border-[#e0c0b2] bg-white/95 backdrop-blur">
      <div className="mx-auto flex h-full max-w-[1200px] items-center justify-between px-6">
        <Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FFF4ED] text-xl font-extrabold text-[#F37021]">F</span><span className="text-base font-bold text-[#a04100]">FSOLVER <span className="font-medium text-slate-500">Đại học FPT</span></span></Link>
        <nav className="flex h-full items-center gap-7">{nav.map(([label, href]) => <Link key={href} to={href} className={`flex h-full items-center border-b-2 text-[13px] font-medium transition-colors ${active === href ? "border-[#F37021] text-[#F37021]" : "border-transparent text-slate-600 hover:text-[#F37021]"}`}>{label}</Link>)}</nav>
        <div className="flex items-center gap-3"><Link to="/dang-nhap" className="text-sm font-semibold text-slate-700">Đăng nhập</Link><Link to="/dong-gop" className="f-btn-primary h-10 px-4">Đóng góp ngay</Link></div>
      </div>
    </header>
    <main>{children}</main>
    <footer className="border-t bg-white"><div className="mx-auto flex max-w-[1200px] items-center justify-between gap-8 px-6 py-8 text-xs text-slate-500"><p><b className="mr-2 text-sm text-[#a04100]">FSOLVER</b> © 2026 Hệ thống Quản trị Quỹ Sinh viên FSOLVER - Đại học FPT</p><div className="flex gap-5 whitespace-nowrap"><span>Về FSOLVER</span><span>Quy trình minh bạch</span><span>Chính sách bảo mật</span><span>Điều khoản sử dụng</span><span>Liên hệ</span></div></div></footer>
  </div>;
}

function Badge({ children, type = "success" }: {children: React.ReactNode; type?: "success" | "warning" | "info" | "neutral"}) {
 const cls = { success: "bg-[#DCFCE7] text-[#166534]", warning: "bg-[#FEF3C7] text-[#92400E]", info: "bg-[#DBEAFE] text-[#1E40AF]", neutral: "bg-slate-100 text-slate-600" }[type]; return <span className={`badge ${cls}`}>{children}</span>;
}
function SectionTitle({ eyebrow, title, copy, action }: {eyebrow?: string; title: string; copy?: string; action?: React.ReactNode}) { return <div className="mb-7 flex items-end justify-between gap-6"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-[#F37021]">{eyebrow}</p>}<h2 className="text-2xl font-bold tracking-tight">{title}</h2>{copy && <p className="mt-2 text-sm text-slate-600">{copy}</p>}</div>{action}</div> }
function Kpis() { return <div className="grid grid-cols-4 gap-4">{[["Tổng huy động", "4,39 tỷ ₫", "Từ 2.847 nhà tài trợ", "#F37021"],["Đã giải ngân", "2,74 tỷ ₫", "62,4% tổng nguồn quỹ", "#0072BC"],["Số dư sẵn sàng", "1,65 tỷ ₫", "Đối soát ngày 18/07", "#00A859"],["Sinh viên đã hỗ trợ", "1.286", "58 dự án đang triển khai", "#7C3AED"]].map(([l,v,s,c])=><div key={l} className="f-card p-5"><div className="mb-4 h-1.5 w-10 rounded-full" style={{backgroundColor:c}}/><p className="text-sm text-slate-500">{l}</p><p className="mt-1 text-2xl font-bold">{v}</p><p className="mt-2 text-xs text-slate-500">{s}</p></div>)}</div> }
function FundCard({ fund }: {fund: typeof funds[number]}) { const [name,risk,desc,balance,progress]=fund; return <article className="f-card flex flex-col p-5"><div className="mb-4 flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#FFF4ED] text-[#F37021]"><Landmark size={21}/></div><Badge type={risk === "Cao" ? "warning" : risk === "TB" ? "info" : "success"}>Rủi ro {risk}</Badge></div><h3 className="font-bold">{name}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-slate-600">{desc}</p><div className="mt-5 flex justify-between text-xs"><span className="text-slate-500">Số dư khả dụng</span><b>{balance}</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#00A859]" style={{width:`${progress}%`}}/></div><div className="mt-5 flex gap-2"><Link to="/dong-gop" className="f-btn-primary h-9 flex-1 px-3 text-xs">Đóng góp</Link><Link to="/cac-quy/quy-hoc-tap" className="f-btn-secondary h-9 flex-1 px-3 text-xs">Chi tiết</Link></div></article> }
function TransactionTable({ limit = 4 }: {limit?: number}) { return <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr>{["Mã giao dịch","Ngày","Loại","Quỹ","Số tiền","Người","Trạng thái",""].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{transactions.slice(0,limit).map(t=><tr className="border-t hover:bg-slate-50" key={t[0]}>{t.map((x,i)=><td key={i} className={`px-4 py-3 ${i===0 ? "font-mono text-xs font-medium" : i===4 ? (x.startsWith("+") ? "font-semibold text-[#16A34A]" : "font-semibold text-[#DC2626]") : ""}`}>{i===6 ? <Badge>{x}</Badge> : x}</td>)}<td className="px-4 py-3"><Link to="/giao-dich/SCF-2026-01842" className="text-[#0072BC]"><Eye size={17}/></Link></td></tr>)}</tbody></table></div> }
function Home(){return <PublicShell><section className="mx-auto max-w-[1200px] px-6 pb-14 pt-20"><div className="relative overflow-hidden rounded-3xl bg-[#FFF4ED] px-14 py-16"><div className="absolute -right-10 -top-12 h-72 w-72 rounded-full border-[36px] border-[#F37021]/10"/><div className="relative max-w-2xl"><p className="mb-4 text-sm font-bold uppercase tracking-[.16em] text-[#a04100]">Nền tảng quản trị quỹ cộng đồng sinh viên</p><h1 className="text-5xl font-extrabold leading-[1.12] tracking-tight">Minh bạch nguồn quỹ.<br/><span className="text-[#F37021]">Lan tỏa niềm tin</span> sinh viên.</h1><p className="mt-6 max-w-xl leading-7 text-slate-600">FSOLVER không trực tiếp giữ tiền. Mọi đóng góp được chuyển về tài khoản của Đoàn Thanh niên, Hội Sinh viên hoặc Phòng CTSV và được công khai xuyên suốt.</p><div className="mt-8 flex gap-3"><Link to="/dong-gop" className="f-btn-primary">Đóng góp ngay <Heart size={17}/></Link><Link to="/minh-bach" className="f-btn-secondary">Xem dashboard minh bạch <ArrowRight size={17}/></Link></div></div></div><div className="-mt-6 relative"><Kpis/></div><section className="pt-16"><SectionTitle eyebrow="7 quỹ đang hoạt động" title="Chọn nơi bạn muốn tạo tác động" copy="Mỗi nguồn quỹ đều có mục tiêu, số dư và nhật ký giao dịch công khai." action={<Link to="/cac-quy" className="text-sm font-semibold text-[#F37021]">Xem tất cả <ChevronRight className="inline" size={16}/></Link>}/><div className="grid grid-cols-3 gap-5">{funds.slice(0,3).map(f=><FundCard key={f[0]} fund={f}/>)}</div></section><section className="grid grid-cols-[1.45fr_1fr] gap-6 pt-16"><div><SectionTitle title="Giao dịch mới được xác thực" action={<Link to="/giao-dich" className="text-sm font-semibold text-[#0072BC]">Nhật ký giao dịch</Link>}/><TransactionTable limit={3}/></div><div className="f-card p-6"><p className="text-sm font-semibold">Thu - chi 6 tháng gần nhất</p><div className="mt-8 flex h-40 items-end gap-4">{[50,76,43,88,62,94].map((h,i)=><div className="flex flex-1 flex-col items-center gap-2" key={i}><div className="w-full rounded-t bg-[#F37021]" style={{height:`${h}%`}}/><span className="text-[10px] text-slate-400">T{i+1}</span></div>)}</div><p className="mt-4 text-xs text-slate-500"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#F37021]"/>Tổng thu theo tháng</p></div></section></section></PublicShell>}

function FundsPage(){return <PublicShell><div className="mx-auto max-w-[1200px] px-6 py-12"><SectionTitle eyebrow="Danh mục quỹ" title="Các quỹ đang hoạt động" copy="Tổng 7 quỹ minh bạch, được quản trị theo mục tiêu tác động."/><div className="mb-7 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="f-input pl-10" placeholder="Tìm kiếm quỹ"/></div><select className="f-input w-44"><option>Tất cả rủi ro</option><option>Thấp</option><option>TB</option><option>Cao</option></select></div><div className="grid grid-cols-3 gap-5">{funds.map(f=><FundCard key={f[0]} fund={f}/>)}</div></div></PublicShell>}
function FundDetail(){return <PublicShell><div className="mx-auto max-w-[1200px] px-6 py-10"><p className="text-sm text-slate-500">Các quỹ <ChevronRight className="inline" size={15}/> Quỹ Học tập</p><div className="mt-5 flex items-start justify-between rounded-2xl bg-[#FFF4ED] p-8"><div><Badge>Rủi ro Thấp</Badge><h1 className="mt-3 text-3xl font-bold">Quỹ Học tập</h1><p className="mt-3 max-w-2xl text-slate-600">Hỗ trợ học phí, tài liệu và các cơ hội học tập thiết thực cho sinh viên FPT.</p></div><Link to="/dong-gop" className="f-btn-primary">Đóng góp cho quỹ</Link></div><div className="mt-6"><Kpis/></div><div className="mt-8 border-b"><div className="flex gap-7 text-sm font-semibold"><span className="border-b-2 border-[#F37021] pb-4 text-[#F37021]">Tổng quan</span><span className="pb-4 text-slate-500">Giao dịch</span><span className="pb-4 text-slate-500">Dự án</span><span className="pb-4 text-slate-500">Hash</span></div></div><div className="grid grid-cols-[1.5fr_1fr] gap-6 pt-7"><div className="f-card p-6"><h3 className="font-bold">Dòng tiền theo quý</h3><div className="mt-7 flex h-44 items-end gap-6">{[35,56,44,71,64,82].map((h,i)=><div key={i} className="flex flex-1 items-end gap-1"><div className="w-1/2 rounded-t bg-[#F37021]" style={{height:`${h}%`}}/><div className="w-1/2 rounded-t bg-[#0072BC]" style={{height:`${h*.7}%`}}/></div>)}</div></div><div className="f-card p-6"><h3 className="font-bold">Chứng từ yêu cầu</h3><p className="mt-4 text-sm leading-6 text-slate-600">Hóa đơn học phí, chứng từ VAT và xác nhận của đơn vị thụ hưởng được lưu kèm mỗi khoản giải ngân.</p><Link to="/log-bat-bien" className="mt-5 inline-block text-sm font-semibold text-[#0072BC]">Xem nhật ký bất biến</Link></div></div><section className="pt-9"><SectionTitle title="Giao dịch gần đây"/><TransactionTable/></section></div></PublicShell>}
function Transparency(){return <PublicShell><div className="mx-auto max-w-[1200px] px-6 py-10"><SectionTitle eyebrow="Dữ liệu công khai" title="Dashboard minh bạch tài chính" copy="Số liệu được đối soát và cập nhật theo từng kỳ." action={<div className="flex gap-2"><button className="f-btn-secondary h-10 px-3 text-xs"><Download size={15}/> Xuất PDF/Excel</button><Link to="/log-bat-bien" className="f-btn-primary h-10 px-3 text-xs"><ShieldCheck size={15}/> Xác minh bất biến</Link></div>}/><div className="mb-6 flex gap-3"><select className="f-input w-44"><option>Học kỳ 2/2026</option></select><select className="f-input w-48"><option>Tất cả quỹ</option></select><input className="f-input w-44" value="01/01/2026" readOnly/></div><Kpis/><div className="mt-6 grid grid-cols-2 gap-6"><div className="f-card p-6"><h3 className="font-bold">Thu và chi theo tháng</h3><div className="mt-8 flex h-48 items-end gap-5">{[45,72,56,90,64,78,86].map((h,i)=><div className="flex flex-1 items-end gap-1" key={i}><div className="w-1/2 rounded-t bg-[#F37021]" style={{height:`${h}%`}}/><div className="w-1/2 rounded-t bg-[#0072BC]" style={{height:`${h*.6}%`}}/></div>)}</div></div><div className="f-card p-6"><h3 className="font-bold">Phân bổ theo quỹ</h3><div className="mt-6 flex items-center gap-8"><div className="grid h-36 w-36 place-items-center rounded-full border-[18px] border-[#F37021] text-center text-sm font-bold">7<br/><span className="font-normal text-slate-500">quỹ</span></div><div className="space-y-3 text-sm">{funds.slice(0,4).map((f,i)=><p key={f[0]}><span className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{backgroundColor:["#F37021","#0072BC","#00A859","#F59E0B"][i]}}/>{f[0]}</p>)}</div></div></div></div><div className="mt-6 grid grid-cols-[1.5fr_1fr] gap-6"><div><SectionTitle title="Giao dịch đã xác thực"/><TransactionTable/></div><div className="f-card p-6"><Hash className="text-[#0072BC]"/><h3 className="mt-4 font-bold">Chuỗi SHA-256</h3><p className="mt-2 text-xs leading-5 text-slate-500">Khối N đã được liên kết với khối N-1. Dữ liệu không thể chỉnh sửa.</p><p className="mt-4 rounded-lg bg-slate-50 p-3 font-mono text-[11px] text-slate-600">7e6d...a81c → 9c44...bb12</p></div></div></div></PublicShell>}
function TransactionsPage(){return <PublicShell><div className="mx-auto max-w-[1200px] px-6 py-10"><SectionTitle eyebrow="Giao dịch công khai" title="Nhật ký giao dịch" copy="Mọi giao dịch đã xác thực đều được hiển thị minh bạch." action={<button className="f-btn-secondary h-10 px-3 text-xs"><Download size={15}/> Xuất dữ liệu</button>}/><div className="f-card mb-6 grid grid-cols-[1.5fr_repeat(3,1fr)] gap-3 p-4"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="f-input pl-9" placeholder="Tìm mã SCF-ID"/></div><select className="f-input"><option>Tất cả loại</option><option>Đóng góp</option><option>Giải ngân</option></select><select className="f-input"><option>Tất cả quỹ</option></select><input className="f-input" value="01/07/2026 - 18/07/2026" readOnly/></div><TransactionTable/><div className="mt-5 flex items-center justify-between text-sm text-slate-500"><span>Hiển thị 1–4 trên 1842 giao dịch</span><div className="flex gap-2"><button className="rounded border px-3 py-1.5">Trước</button><button className="rounded bg-[#FFF4ED] px-3 py-1.5 text-[#F37021]">1</button><button className="rounded border px-3 py-1.5">Sau</button></div></div><div className="f-card mt-7 flex items-center gap-4 p-5"><Hash className="text-[#0072BC]"/><div><p className="font-semibold">Được bảo vệ bởi log bất biến</p><p className="text-sm text-slate-500">Xác minh lịch sử giao dịch qua chuỗi SHA-256.</p></div><Link className="ml-auto text-sm font-semibold text-[#0072BC]" to="/log-bat-bien">Xem hash</Link></div></div></PublicShell>}
function TransactionDetail(){return <PublicShell><div className="mx-auto max-w-[1000px] px-6 py-10"><p className="text-sm text-slate-500">Giao dịch <ChevronRight className="inline" size={15}/> Chi tiết giao dịch</p><div className="f-card mt-5 overflow-hidden"><div className="border-b bg-[#F8FAFC] p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-sm text-slate-500">SCF-2026-01842</p><h1 className="mt-2 text-2xl font-bold">Đóng góp cho Quỹ Học tập</h1></div><Badge>Đã xác thực</Badge></div></div><div className="grid grid-cols-2 gap-x-10 gap-y-6 p-7 text-sm">{[["Ngày ghi nhận","18/07/2026 · 10:32"],["Số tiền","5.000.000 ₫"],["Quỹ","Quỹ Học tập"],["Người đóng góp","Nguyễn Minh Anh"],["Mục đích","Học bổng kỳ Thu 2026"],["Người phê duyệt","Trần Quốc Bảo · Phòng CTSV"]].map(([l,v])=><div key={l}><p className="text-slate-500">{l}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div><div className="border-t p-7"><h3 className="font-bold">Chứng từ kèm theo</h3><div className="mt-4 flex gap-3"><div className="flex h-28 w-40 flex-col items-center justify-center rounded-lg border border-dashed text-xs text-slate-500"><FileText size={24}/><span className="mt-2">Ủy nhiệm chi.pdf</span></div><div className="flex h-28 w-40 flex-col items-center justify-center rounded-lg border border-dashed text-xs text-slate-500"><CircleAlert size={24}/><span className="mt-2">Video không khả dụng</span></div></div></div><div className="border-t bg-slate-50 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-[#16A34A]"/><div><p className="font-semibold">Hash đã được xác minh</p><p className="font-mono text-xs text-slate-500">N: 7e6d...a81c · N-1: 03af...9b34</p></div></div></div></div></div></PublicShell>}
function Donate(){return <PublicShell><div className="mx-auto grid max-w-[1120px] grid-cols-2 gap-6 px-6 py-12"><section><p className="text-xs font-bold uppercase tracking-[.16em] text-[#F37021]">Cùng tạo tác động</p><h1 className="mt-3 text-3xl font-bold">Đóng góp minh bạch, lan tỏa niềm tin</h1><p className="mt-3 text-slate-600">FSOLVER không giữ tiền thật. Vui lòng chuyển khoản trực tiếp tới tài khoản của đơn vị quản lý quỹ.</p><div className="f-card mt-6 p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Tài khoản nhận đóng góp</p><p className="mt-1 text-lg font-bold">ĐOÀN THANH NIÊN ĐẠI HỌC FPT</p><p className="font-mono text-base font-bold text-[#a04100]">1028 6868 88 · Vietcombank</p></div><button className="rounded-lg border p-3 text-[#0072BC]"><Copy size={19}/></button></div><div className="mt-6 grid h-44 w-44 place-items-center rounded-xl bg-slate-100 text-sm font-semibold text-slate-500">VietQR</div><p className="mt-5 rounded-lg bg-[#FFF4ED] p-3 text-xs leading-5 text-[#92400E]">FSOLVER chỉ ghi nhận và minh bạch hóa khoản đóng góp; website không trực tiếp giữ tiền.</p></div></section><section className="f-card p-7"><h2 className="text-xl font-bold">Gửi thông tin đóng góp</h2><p className="mt-2 text-sm text-slate-500">Đối soát giao dịch nhanh hơn khi có chứng từ.</p><div className="mt-6 space-y-4"><label><span className="f-label">Họ và tên</span><input className="f-input" placeholder="Nguyễn Văn A"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox"/> Đóng góp ẩn danh</label><div className="grid grid-cols-2 gap-3"><label><span className="f-label">Số tiền</span><input className="f-input" placeholder="0 ₫"/></label><label><span className="f-label">Ngày chuyển khoản</span><input className="f-input" value="18/07/2026" readOnly/></label></div><label><span className="f-label">Quỹ muốn đóng góp</span><select className="f-input"><option>Quỹ Học tập</option>{funds.slice(1).map(x=><option key={x[0]}>{x[0]}</option>)}</select></label><label><span className="f-label">Ảnh giao dịch</span><button className="flex h-20 w-full items-center justify-center gap-2 rounded-lg border border-dashed text-sm text-slate-500"><Upload size={17}/> Tải ảnh chứng từ (tối đa 20MB)</button></label><Link to="/dong-gop/thanh-cong" className="f-btn-primary w-full">Gửi thông tin đóng góp</Link></div></section></div></PublicShell>}
function DonateSuccess(){return <PublicShell><div className="mx-auto max-w-[760px] px-6 py-20 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#DCFCE7] text-[#16A34A]"><Check size={32}/></div><h1 className="mt-6 text-3xl font-bold">Đã gửi thông tin đóng góp</h1><p className="mx-auto mt-3 max-w-xl text-slate-600">Cảm ơn bạn đã đồng hành. Khoản đóng góp sẽ được đối soát với đơn vị quản lý quỹ trước khi công khai.</p><div className="f-card mt-8 p-6 text-left"><div className="flex justify-between border-b pb-5"><span className="text-sm text-slate-500">Mã biên nhận</span><b className="font-mono">SCF-DON-2026-01842</b></div><div className="mt-6 grid grid-cols-4 gap-2 text-center text-xs">{["Gửi thông tin","Đối soát","Cộng vào quỹ","Gửi email"].map((x,i)=><div key={x} className="relative"><div className={`mx-auto grid h-8 w-8 place-items-center rounded-full ${i===0 ? "bg-[#16A34A] text-white" : "bg-slate-100 text-slate-500"}`}>{i===0?<Check size={15}/>:i+1}</div><p className="mt-2">{x}</p></div>)}</div></div><div className="mt-8 flex justify-center gap-3"><Link to="/giao-dich" className="f-btn-primary">Xem nhật ký giao dịch</Link><Link to="/minh-bach" className="f-btn-secondary">Dashboard minh bạch</Link></div></div></PublicShell>}
function PublicScore(){return <PublicShell><div className="mx-auto max-w-[1000px] px-6 py-10"><p className="text-sm text-slate-500">Dự án <ChevronRight className="inline" size={15}/> Công khai điểm</p><div className="mt-5 rounded-2xl bg-[#FFF4ED] p-8"><Badge>Đã phê duyệt</Badge><h1 className="mt-3 text-3xl font-bold">Lớp học số cho học sinh vùng cao</h1><p className="mt-3 text-slate-600">Dự án thuộc Quỹ Vùng cao · Kỳ xét duyệt Hè 2026</p></div><div className="mt-6 grid grid-cols-[.75fr_1.25fr] gap-6"><div className="f-card p-6 text-center"><p className="text-sm text-slate-500">Điểm trung bình</p><p className="mt-3 text-5xl font-extrabold text-[#F37021]">87<span className="text-xl">/100</span></p><p className="mt-3 text-sm font-semibold text-[#166534]">Đạt điều kiện phê duyệt</p></div><div className="f-card p-6"><h2 className="font-bold">Nhận xét công khai</h2><div className="mt-4 space-y-4 text-sm"><div className="border-l-2 border-[#F37021] pl-4"><p>"Kế hoạch triển khai rõ ràng, tác động phù hợp với mục tiêu quỹ."</p><p className="mt-1 text-xs text-slate-500">Hội đồng xét duyệt · Danh tính ẩn</p></div><div className="border-l-2 border-[#0072BC] pl-4"><p>"Ngân sách hợp lý, hồ sơ báo giá đầy đủ."</p><p className="mt-1 text-xs text-slate-500">Hội đồng xét duyệt · Danh tính ẩn</p></div></div></div></div></div></PublicShell>}
function ImmutableLog(){return <PublicShell><div className="mx-auto max-w-[1200px] px-6 py-10"><SectionTitle eyebrow="NFR-06" title="Trình xem log bất biến" copy="Theo dõi và xác minh chuỗi sự kiện đã được ghi nhận." action={<button className="f-btn-secondary h-10 px-3 text-xs"><Download size={15}/> Xuất log</button>}/><div className="mb-6 flex items-center gap-3 rounded-xl border border-[#bbf7d0] bg-[#f0fdf4] p-4 text-sm text-[#166534]"><ShieldCheck size={20}/><span className="font-semibold">Chuỗi log hợp lệ.</span> 1.842 sự kiện đã được kiểm tra, không phát hiện đứt gãy.</div><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-slate-500"><tr>{["Sự kiện","Thời gian","Hash hiện tại","Hash trước đó","Trạng thái"].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{transactions.map((t,i)=><tr className="border-t" key={t[0]}><td className="px-5 py-4"><p className="font-semibold">{i%2===0?"Ghi nhận đóng góp":"Xác nhận giải ngân"}</p><p className="font-mono text-xs text-slate-500">{t[0]}</p></td><td className="px-5 py-4 text-slate-600">{t[1]} · 10:32</td><td className="px-5 py-4 font-mono text-xs">7e6d...a81{i}</td><td className="px-5 py-4 font-mono text-xs">03af...9b3{i}</td><td className="px-5 py-4"><Badge>Hợp lệ</Badge></td></tr>)}</tbody></table></div><div className="f-card mt-6 p-5"><div className="flex items-center gap-4"><LockKeyhole className="text-[#0072BC]"/><div><p className="font-semibold">Nguyên tắc bất biến</p><p className="text-sm text-slate-500">Mỗi bản ghi tham chiếu đến hash của bản ghi trước đó; mọi thay đổi đều có thể bị phát hiện.</p></div></div></div></div></PublicShell>}

export default function Index(){ const { pathname }=useLocation(); if(pathname==="/cac-quy") return <FundsPage/>; if(pathname==="/cac-quy/quy-hoc-tap") return <FundDetail/>; if(pathname==="/minh-bach") return <Transparency/>; if(pathname==="/giao-dich") return <TransactionsPage/>; if(pathname.startsWith("/giao-dich/")) return <TransactionDetail/>; if(pathname==="/dong-gop") return <Donate/>; if(pathname==="/dong-gop/thanh-cong") return <DonateSuccess/>; if(pathname==="/cong-khai-diem") return <PublicScore/>; if(pathname==="/log-bat-bien") return <ImmutableLog/>; return <Home/>; }
